# Generated by Django 4.0.4 on 2022-06-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_comment_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(blank=True, max_length=200)),
                ('cEmail', models.CharField(blank=True, max_length=200)),
                ('cContact', models.CharField(blank=True, max_length=200)),
                ('cMessage', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contactinfo',
            },
        ),
    ]
