# Generated by Django 4.0.4 on 2022-06-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contactinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='cContact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='cEmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='cMessage',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='cName',
            new_name='name',
        ),
    ]
