# Generated by Django 4.0.4 on 2022-06-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('metaDesc', models.CharField(max_length=100)),
                ('metaKey', models.CharField(max_length=100)),
                ('logo', models.FileField(null=True, upload_to='news/')),
                ('favicon', models.FileField(null=True, upload_to='news/')),
                ('aboutimg', models.FileField(null=True, upload_to='news/')),
                ('abouttitle', models.CharField(max_length=100)),
                ('aboutdesc', models.TextField(max_length=1000)),
            ],
        ),
    ]
