# Generated by Django 4.0.4 on 2022-05-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Cateory',
        ),
    ]
