# Generated by Django 4.0.4 on 2022-06-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='aboutimg',
            field=models.FileField(null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='favicon',
            field=models.FileField(null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.FileField(null=True, upload_to='site/'),
        ),
    ]
