# Generated by Django 4.0.4 on 2022-05-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
