# Generated by Django 4.0.4 on 2022-06-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_site_aboutimg_alter_site_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'Newsletter',
            },
        ),
    ]
