# Generated by Django 4.0.4 on 2022-06-23 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
