# Generated by Django 4.0.4 on 2022-05-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
