# Generated by Django 4.0.4 on 2022-06-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_newsletter_timestamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='site',
            table='Sitesetting',
        ),
    ]
