# Generated by Django 4.0.4 on 2022-06-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_site_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='aboutdesc',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='aboutimg',
            field=models.FileField(null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='abouttitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='favicon',
            field=models.FileField(null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.FileField(null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='metaDesc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='metaKey',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
