# Generated by Django 4.0.4 on 2022-06-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_alter_site_aboutdesc_alter_site_aboutimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='aboutdesc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='aboutimg',
            field=models.FileField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='abouttitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='metaDesc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='metaKey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
