# Generated by Django 4.0.4 on 2022-05-23 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_category_table'),
        ('editors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='category',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.category'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.FileField(upload_to='news/'),
        ),
    ]
