# Generated by Django 4.0.4 on 2022-05-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0002_alter_newsmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.FileField(null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
