# Generated by Django 4.0.4 on 2022-05-23 11:47

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0003_alter_newsmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='content',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
