# Generated by Django 4.0.4 on 2022-05-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0005_alter_newsmodel_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='upload_to',
            new_name='updated_at',
        ),
    ]
