# Generated by Django 4.0.4 on 2022-06-02 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editors', '0006_rename_upload_to_newsmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
